apiVersion: integration/v1
kind: Step
name: apply
version: 1
summary: Apply a Terraform configuration
description: |
  Applies the given Terraform module or plan. The outputs of this
  step are the same as the Terraform outputs.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/terraform-step-apply
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Terraform apply
  content:
    apiVersion: v1
    kind: Step
    name: terraform-step-apply
    image: relaysh/terraform-step-apply
    spec:
      directory: !Parameter directory
      git:
        connection: !Connection {type: ssh, name: my-ssh-connection}
        name: !Parameter name
        branch: !Parameter gitBranch
        repository: !Parameter gitRepository
      google:
        connection: !Connection {type: gcp, name: my-gcp-connection}
      workspace: !Secret workspace
