apiVersion: integration/v1
kind: Step
name: apply
version: 1
summary: Apply a Terraform configuration
description: |
  This step will apply the given Terraform module or plan. The outputs of this
  step are the same as the Terraform outputs.
build:
  apiVersion: build/v1
  kind: Docker
