apiVersion: integration/v1
kind: Step
name: plan
version: 1
summary: Plan a Terraform configuration
description: |
  Outputs the plan of the given Terraform module.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/terraform-step-plan
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
examples:
- summary: Terraform plan
  content:
    apiVersion: v1
    kind: Step
    name: terraform-step-plan
    image: relaysh/terraform-step-plan
    spec:
      directory: !Parameter directory
      git:
        connection: !Connection {type: ssh, name: my-ssh-connection}
        name: !Parameter name
        branch: !Parameter gitBranch
        repository: !Parameter gitRepository
      google:
        connection: !Connection {type: gcp, name: my-gcp-connection}
      workspace: !Secret workspace
